# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchFromGitHub,
}:
{
  ferium = {
    pname = "ferium";
    version = "9d6f16a5397edbfde8cbe82c0e6657355105b7e1";
    src = fetchFromGitHub {
      owner = "gorilla-devs";
      repo = "ferium";
      rev = "9d6f16a5397edbfde8cbe82c0e6657355105b7e1";
      fetchSubmodules = false;
      sha256 = "sha256-Y0O/DRAh4+pGgUnibOYsgxLb0iej8zzxDB2gwm+KLpI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-Y0O_DRAh4+pGgUnibOYsgxLb0iej8zzxDB2gwm+KLpI=/Cargo.lock";
      outputHashes = {

      };
    };
    date = "2026-05-16";
  };
  "fzf-tab.fish" = {
    pname = "fzf-tab.fish";
    version = "22326fa2d51e771b8253eb8bf1eb72e635a9d303";
    src = fetchFromGitHub {
      owner = "xxxbrian";
      repo = "fzf-tab.fish";
      rev = "22326fa2d51e771b8253eb8bf1eb72e635a9d303";
      fetchSubmodules = false;
      sha256 = "sha256-Itmk9COzXeFSZS9nHMcPkPTgh4bJx/0W3IvekFmt2Tw=";
    };
    date = "2026-03-26";
  };
  "gvfs.yazi" = {
    pname = "gvfs.yazi";
    version = "3abc0a258f9d7aeaa453a2d0d6e103c5a305953d";
    src = fetchFromGitHub {
      owner = "boydaihungst";
      repo = "gvfs.yazi";
      rev = "3abc0a258f9d7aeaa453a2d0d6e103c5a305953d";
      fetchSubmodules = false;
      sha256 = "sha256-UHneVJ+YXyDuPrZS+PZbs9n9h+VN5M2QG36FdprBkJc=";
    };
    date = "2026-03-30";
  };
  nomm = {
    pname = "nomm";
    version = "0.8.0";
    src = fetchFromGitHub {
      owner = "Allexio";
      repo = "nomm";
      rev = "0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-m2OXKfqHSTEAGkkrsMXjOMkwBJ2dZgyh4nYjdv2a8l0=";
    };
  };
}
